/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407_xx_MemMap.h"
#include "gpio.h"
#include "uart.h"

#include "bootloader.h"
#include "bl_cmd_packets.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void sw_delay()
{
	for(volatile uint8_t i =0; i<500;i++);
}
int main(void)
{
	extern volatile uint8_t usart_command;
	extern volatile uint8_t command_recieved;
	char string_array[] = "Hi,From BootLoader!!!";
	char bl_continue_flag = '0';

	gpio_user_cfg_init();
	usart_init();

	USART_RegDef_Struct* pUsart = USART2;
    if(gpio_pin_read(GPIOB,GPIO_PIN_5))
    {

       do
       {

    	   //bl_continue_flag = '0';
		   usart_send_string(pUsart, "*=============================================================*\n\r");
		   usart_send_string(pUsart, "|                           MENU                              |\n\r");
		   usart_send_string(pUsart, "|                 STM32F407 DISC BOOTLOADER V1                |\n\r");
		   usart_send_string(pUsart, "*=============================================================*\n\r\n\r");
		   usart_send_string(pUsart, "   Which BL command you want to send ?\n\r\n\r");
		   usart_send_string(pUsart, "   BL_GET_VER                                              --> 1\n\r");
		   usart_send_string(pUsart, "   BL_GET_HELP                                             --> 2\n\r");
		   usart_send_string(pUsart, "   EXIT_MENU                                               --> 0\n\r\n\r");
		   usart_send_string(pUsart, "   Enter The Command Code:");


		   while(!command_recieved);

		   command_recieved = 0;
		   usart_send_char(pUsart, usart_command);
		  // extern volatile uint8_t tx_packet_buffer[6] = {0};//this should be initialized to zero
		   usart_send_string(pUsart, "\n\r\n\r");
		   switch(usart_command)
		   {
			  case '1':
				   usart_send_string(pUsart, "Command Requested : 0x51(BL_GET_VER) \n\r");
				   build_bl_packets(usart_command);
				   bootloader_uart_read_data();
				   break;
			  case '2':
				   usart_send_string(pUsart, "Command Requested : 0x52(BL_GET_HELP) \n\r");
				   build_bl_packets(usart_command);
				   bootloader_uart_read_data();
				   break;
			  case '3':
				   usart_send_string(pUsart, "Command Requested : 0x53(BL_GET_CID) \n\r");
				   build_bl_packets(usart_command);
				   bootloader_uart_read_data();
				   break;

			  default:
				   usart_send_string(pUsart, "Invalid command\n\r");
				   break;
		   }

		   usart_send_string(pUsart, "Continue in BootLoader(y/n):");

		   while(!command_recieved);
		   command_recieved = 0;
		   usart_send_char(pUsart, usart_command);
		   usart_send_string(pUsart, "\n\r\n\r");
		   switch(usart_command)
		   {
		       case 'n':
		   		  {
		   			 usart_send_string(pUsart, "Entering User application");
		   			 bootloader_jump_to_user_app();
		   			 break;
		   		  }
		       case	'y':
		       {
		    	     usart_send_string(pUsart, "You have entered 'y',Continuing in BootLoader Mode!!!\r\n\r\n");
		    	     bl_continue_flag = usart_command;
		    	     break;
		       }
		       default:
		       {
		    	    usart_send_string(pUsart, "You have entered invalid command,Continuing in BootLoader Mode!!!\r\n\r\n");
		    	   	bl_continue_flag = usart_command;
		    	   	break;
		       }
		   }


       }
	   while(bl_continue_flag);



    }
    else
    {
    	usart_send_string(pUsart, "Entering User application");
    	bootloader_jump_to_user_app();
    }

}
